### ISSUE TITLE
Frontrunning the tx could be possible for MEV

### ISSUE THREAD

**Issue by cleanunicorn** [fiatdao/actions#6]
**Description**

A user can call `.sellCollateralAndModifyDebt()` to sell some `fCash` tokens. This is achieved in the private method `_sellfCash()`

https://github.com/fiatdao/actions/blob/ccc6dd81bcc48765741ff54d483ed0f7f290f251/src/vault/VaultFCActions.sol#L410-L411

The method `._sellfCash()` sells some tokens on the market and returns the amount of tokens received.

https://github.com/fiatdao/actions/blob/ccc6dd81bcc48765741ff54d483ed0f7f290f251/src/vault/VaultFCActions.sol#L542-L550

The returned value is not used in `.sellCollateralAndModifyDebt()`

https://github.com/fiatdao/actions/blob/ccc6dd81bcc48765741ff54d483ed0f7f290f251/src/vault/VaultFCActions.sol#L410-L411

This returned value could be used in a `require/error` statement to make sure a minimum expected amount of tokens was received. Having a statement that requires a minimum amount of tokens should protect from MEV attacks, sandwiching the transaction.

**Recommendation**

Use the returned value to make sure an expected amount of tokens is obtained at the end of the tx, protecting from sandwich attacks.

**Comment by SolcAndMe** [comment]
Frontrunning protection exists via the minImpliedRate and maxImpliedRate arguments.
